# -*- coding: utf-8 -*-
"""french-summarisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c5StH0fWiPsPwUfYyk7mR6KhTmy7J846

#### USING PIPELINES FOR NLP TASKS

https://huggingface.co/transformers/main_classes/pipelines.html#transformers.SummarizationPipeline

https://huggingface.co/plguillou/t5-base-fr-sum-cnndm

https://huggingface.co/models?filter=en&pipeline_tag=summarization
"""
from transformers import pipeline

text = """La tour fait 324 mètres (1,063 pieds) de haut, environ la même hauteur qu'un immeuble de 81 étages, et est la plus haute structure de Paris. 
Sa base est carrée, mesurant 125 mètres (410 pieds) sur chaque côté.
Durant sa construction, la tour Eiffel surpassa le Washington Monument pour devenir la plus haute structure construite  
par l'homme dans le monde, un titre qu'elle conserva pendant 41 ans jusqu'à l'achèvement du Chrysler Building à New-York City en 1930.
Ce fut la première structure à atteindre une hauteur de 300 mètres. Avec l'ajout d'une antenne de radiodiffusion au sommet de la tour Eiffel en 1957, 
celle-ci redevint plus haute que le Chrysler Building de 5,2 mètres (17 pieds).  
En excluant les transmetteurs, elle est la seconde plus haute stucture autoportante de France après le viaduc de Millau.
"""

hugging_face_pretrained_model = "plguillou/t5-base-fr-sum-cnndm"
print(f"## OK : will use this nlp pretrained model : {hugging_face_pretrained_model}")
# summarizer = pipeline("summarization", model=hugging_face_pretrained_model, tokenizer="t5-base")
print(f"## OK : will load the nlp pipeline model : {hugging_face_pretrained_model}")
summarizer = pipeline("summarization", model=hugging_face_pretrained_model, tokenizer=hugging_face_pretrained_model)
print(f"## OK : now trying to summarize the text ... ")
result = summarizer(text, min_length=5, max_length=200)
print(f"## OK : the summarize of the text is ready \n{result} ")
print('#'*80)
print(f"original text length : {len(text)}, original text: \n{text}")
print('='*80)
summary_text = result[0]['summary_text'].replace('. ', ".\n")
print(f"summary length : {len(summary_text)}, summary: \n{summary_text}")

